language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=x86_64-unknown-linux-musl

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - rustup target add $TARGET || true

script:
  - cargo build --target $TARGET
  - cargo build --target $TARGET --release
  - cargo test --target $TARGET
  - cargo test --target $TARGET --release

notifications:
  email:
    on_success: never
