name: Release MSI

on:
  push:
    tags:
      - '*'

jobs:
  build-winetd-msi:
    runs-on: windows-latest
    steps:
      - uses: hecrj/setup-rust-action@master
      - uses: actions/checkout@master
      - name: Cargo build
        run: cargo build --release --no-default-features --features loggest
      - name: Download WiX
        shell: cmd
        run: curl.exe -LS https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe > wix311.exe
      - name: Install WiX
        shell: cmd
        run: wix311.exe /install /quiet /norestart
      - name: Prepare MSI file
        shell: cmd
        run: '"%PROGRAMFILES(x86)%\WiX Toolset v3.11\bin\candle.exe" "fscmp.wxs"'
      - name: Link MSI
        shell: cmd
        run: '"%PROGRAMFILES(x86)%\WiX Toolset v3.11\bin\light.exe" "fscmp.wixobj" "-out" "fscmp-%GITHUB_REF%.msi"'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ format('fscmp-{0}.msi', github.ref) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
