name: CI

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
    - uses: actions/checkout@master
    - name: Format
      run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
    - uses: actions/checkout@master
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
    - uses: hecrj/setup-rust-action@master
    - name: Install musl
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt install musl-tools
    - name: Add target
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: rustup target add ${{ matrix.target }}
    - uses: actions/checkout@master
    - name: Check debug
      run: cargo check --all-targets --all-features --target ${{ matrix.target }}
    - name: Check release
      run: cargo check --all-targets --all-features --target ${{ matrix.target }} --release

  test:
    runs-on: ubuntu-latest
    needs: [format, lint, build]
    strategy:
      matrix:
        rust: [stable, nightly]
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install dependencies
      run: sudo apt install libpcap-dev
    - name: Install musl
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt install musl-tools
    - name: Add target
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: rustup target add ${{ matrix.target }}
    - uses: actions/checkout@master
    - name: Test debug
      run: cargo test --all-features --target ${{ matrix.target }}
      env:
        RUST_MIN_STACK: 8388608
    - name: Test release
      run: cargo test --all-features --target ${{ matrix.target }}
      env:
        RUST_MIN_STACK: 8388608
